In [66]:
from nltk import tokenize
p= 'Good moring Dr. Adams. The patient is waiting for you in room !'
tokenize.sent_tokenize(p)

['Good moring Dr. Adams.', 'The patient is waiting for you in room !']

In [67]:
import nltk 
sentence ="""At eight o'clock on Thursday morning ... Arthus didn't feel very good """
tokens=nltk.word_tokenize(sentence)
tokens


['At',
 'eight',
 "o'clock",
 'on',
 'Thursday',
 'morning',
 '...',
 'Arthus',
 'did',
 "n't",
 'feel',
 'very',
 'good']

In [68]:
from nltk.tokenize import word_tokenize 
from gensim.corpora.dictionary import Dictionary

sometext= "Hello how are you doing"
tokens =word_tokenize(sometext)
my_vocab =Dictionary([tokens])
print(my_vocab.token2id['are'])

1


In [69]:
import nltk
from keras.preprocessing.text import Tokenizer

In [116]:
# texts=['He is a teacher','She is a teacher','she and he are teacher', 'he is a student and she is a student']
# sentences = []
# for sent in texts:
#     sentences.append(nltk.word_tokenize(sent))
# print(sentences)

In [117]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

In [118]:
print(tokenizer.word_index)


{'.': 1, 'i': 2, 'to': 3, 'you': 4, ',': 5, '?': 6, 'a': 7, '!': 8, 'the': 9, 'u': 10, '...': 11, 'and': 12, '&': 13, 'is': 14, 'in': 15, 'me': 16, ';': 17, 'my': 18, 'it': 19, ':': 20, 'for': 21, '..': 22, 'your': 23, 'of': 24, 'have': 25, 'call': 26, 'that': 27, 'do': 28, 'on': 29, ')': 30, "'s": 31, 'now': 32, 'are': 33, '2': 34, 'so': 35, 'not': 36, 'but': 37, 'or': 38, 'can': 39, 'at': 40, 'we': 41, "'m": 42, 'get': 43, 'if': 44, 'ur': 45, 'with': 46, 'be': 47, 'will': 48, 'just': 49, "n't": 50, 'no': 51, 'this': 52, 'gt': 53, 'lt': 54, '*': 55, 'up': 56, 'how': 57, 'when': 58, '4': 59, '#': 60, 'from': 61, 'what': 62, "''": 63, 'go': 64, 'free': 65, 'all': 66, 'out': 67, 'ok': 68, 'know': 69, 'got': 70, 'like': 71, 'was': 72, 'good': 73, 'then': 74, "'ll": 75, 'come': 76, '-': 77, 'there': 78, 'he': 79, 'am': 80, 'its': 81, 'time': 82, 'only': 83, 'day': 84, 'love': 85, 'want': 86, 'send': 87, 'text': 88, 'as': 89, 'one': 90, 'going': 91, 'by': 92, 'txt': 93, 'about': 94, 'need':

In [119]:
X= tokenizer.texts_to_matrix(sentences,mode='count')
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 1. 1. 0.]
 [0. 0. 2. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]]


In [120]:
import pandas as pd
import numpy as np
import nltk


In [121]:
filename = 'spam.csv'
df = pd.read_csv(filename, encoding='latin-1')
#print(df.shape)
# print(df.columns)
# print(df.head(2))
# print(df)


In [122]:
data = df.values
print(data.shape)


(5572, 5)


In [123]:
print(data[:2])

[['ham'
  'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
  nan nan nan]
 ['ham' 'Ok lar... Joking wif u oni...' nan nan nan]]


In [124]:
lines= data[:,1]
labels = data[:,0]
print(lines[:5])
print(labels[:20])


['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 'U dun say so early hor... U c already then say...'
 "Nah I don't think he goes to usf, he lives around here though"]
['ham' 'ham' 'spam' 'ham' 'ham' 'spam' 'ham' 'ham' 'spam' 'spam' 'ham'
 'spam' 'spam' 'ham' 'ham' 'spam' 'ham' 'ham' 'ham' 'spam']


In [125]:
#tach tu
sentences = [nltk.word_tokenize(sent) for sent in lines]
print(sentences[0])

['Go', 'until', 'jurong', 'point', ',', 'crazy', '..', 'Available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet', '...', 'Cine', 'there', 'got', 'amore', 'wat', '...']


In [126]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)


In [127]:
X = tokenizer.texts_to_matrix(sentences, mode='binary')
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 1. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]]


In [128]:
from sklearn.model_selection import train_test_split
X_train,X_test, Y_train, Y_test=train_test_split(X, labels, test_size=0.2,random_state=0)


In [129]:
from sklearn.linear_model import LogisticRegression
model_LR = LogisticRegression()
model_LR = model_LR.fit(X_train, Y_train)
y_pred = model_LR.predict(X_test)

In [130]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       949
        spam       0.99      0.89      0.93       166

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [131]:
input_sent = 'she is a teacher'
input_sentences =[nltk.word_tokenize(input_sent)]
print(input_sentences)

[['she', 'is', 'a', 'teacher']]


In [132]:
X_input = tokenizer.texts_to_matrix(input_sentences, mode='binary')
print(X_input)



[[0. 0. 0. ... 0. 0. 0.]]


In [133]:
y_pred = model_LR.predict(X_input)
print(y_pred)

['ham']


              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       949
        spam       0.99      0.89      0.93       166

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

